import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}

// app/layout.js
import { Playfair_Display } from 'next/font/google'
import './globals.css'

// Initialize the font
const playfair = Playfair_Display({ 
  subsets: ['latin'],
  variable: '--font-playfair' // Custom variable for Tailwind
})

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={playfair.variable}>
        {children}
      </body>
    </html>
  )
}